Fixed issue when `python.jediEnabled` setting was not removed and `python.languageServer` setting was not updated.
